spring.application.name=studentportal

# Database Configuration
# Must migrate to Flyway before production deployment.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:studentportal;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf Configuration
spring.thymeleaf.cache=false

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

management.endpoint.shutdown.enabled=true
management.endpoints.web.exposure.include=shutdown
management.endpoint.shutdown.web.enabled=true
